<!-- <div id="preloader"></div> -->    
<script src="../lib/jquery/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/js/chart.min.js"></script>
<script src="assets/js/bs-init.js"></script>
<script src="assets/js/theme.js"></script>
<script src="../lib/node_modules/sweetalert2/dist/sweetalert2.all.min.js"></script>
<script src="../js/modules/copyright.module.js"></script>
<script src="../js/modules/preLoader.js"></script>
